---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Add the user 'wouter' with a specific uid and a primary group of 'admin'
    ansible.builtin.user:
      name: wouter
      shell: /bin/bash
      comment: Wouter Spaans
      uid: 1040
      groups: 
        - adm
        - cdrom
        - sudo
        - dip
        - plugdev
        - lxd
      password: $6$i2Tj/l3o5rH2XQDr$EXbxoUdukY4x8mjR2OUz4f53lU9EGk6xh9fvJomNZllsgIjJyrFkFoT2Lq2k3qsPiDea9jOZ7ZMDP1w3MjJ8p/

  - name: Enable auto logon AutomaticLoginEnable
    lineinfile:
      path: /etc/gdm3/custom.conf
      regexp: '^#  AutomaticLoginEnable = true'
      line: '  AutomaticLoginEnable = true'
      owner: root
      group: root
      mode: '0644'
    
  - name: Enable auto logon AutomaticLogin 
    lineinfile:
      path: /etc/gdm3/custom.conf
      regexp: '^#  AutomaticLogin = user1'
      line: '  AutomaticLogin = wouter'
      owner: root
      group: root
      mode: '0644'

  - name: Wait for unlocking /var/lib/dpkg/lock
    become: yes
    shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;  

  - name: download ms product repository
    get_url:
      url: https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb
      dest: /tmp/packages-microsoft-prod.deb

  - name: install ms product repository
    apt: deb=/tmp/packages-microsoft-prod.deb
    become: true

  - name: install apt packages
    package:
      name:
        - python3-pip
        - npm
        - open-vm-tools-desktop
        - gnome-software
        - apt-transport-https
        - openjdk-8-jdk

  - name: Install .NET Core SDK
    apt:
      name: dotnet-sdk-5.0
      state: present
      update_cache: yes
    become: true

  - name: install psutil
    pip:
      name:
        - psutil

  - name: install brave
    community.general.snap:
      name:
        - brave
        
  - name: install bitwarden
    community.general.snap:
      name:
        - bitwarden
        
  - name: install androidsdk
    community.general.snap:
      name:
        - androidsdk

  - name: install android-studio
    community.general.snap:
      name: android-studio
      classic: yes

  - name: install vscode
    community.general.snap:
      name: code
      classic: yes
      
  - name: install vscode extention dotnettools
    become_user: wouter
    shell: code --install-extension ms-dotnettools.csharp

  - name: install vscode extention soltion explorer
    become_user: wouter
    shell: code --install-extension fernandoescolar.vscode-solution-explorer

  - name: set favorites
    become_user: wouter
    dconf:
      key: "/org/gnome/shell/favorite-apps"
      value: "['org.gnome.Nautilus.desktop', 'snap-store_ubuntu-software.desktop', 'brave_brave.desktop', 'code_code.desktop', 'org.gnome.Terminal.desktop', 'bitwarden_bitwarden.desktop']"

  - name: set desktop idle-delay
    become_user: wouter
    dconf:
      key: "/org/gnome/desktop/session/idle-delay"
      value: "uint32 0"

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/wouter/.bashrc
      owner: wouter
      group: wouter

  - name: Creates directory
    file:
      path: /home/wouter/repos
      owner: wouter
      group: wouter
      mode: '0755'
      state: directory
      
  - name: Install "nativescript" node.js package globally.
    community.general.npm:
      name: nativescript
      global: yes

  - name: Creates directory Android/Sdk/cmdline-tools/latest
    file:
      path: /home/wouter/Android/Sdk/cmdline-tools/latest
      owner: wouter
      group: wouter
      mode: '0755'
      state: directory

  - name: Download commandlinetools-linux-7583922_latest.zip
    ansible.builtin.unarchive:
      src: https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
      dest: /home/wouter/Android/Sdk/cmdline-tools/latest
      owner: wouter
      group: wouter
      mode: '0755'
      remote_src: yes
      
  - name: Creates directory Android/Sdk/system-images/android-30/google_apis_playstore/x86
    file:
      path: /home/wouter/Android/Sdk/system-images/android-30/google_apis_playstore/x86
      owner: wouter
      group: wouter
      mode: '0755'
      state: directory

  - name: Download android-30/google_apis_playstore/x86
    ansible.builtin.unarchive:
      src: https://dl.google.com/android/repository/sys-img/google_apis_playstore/x86-30_r09-linux.zip
      dest: /home/wouter/Android/Sdk/system-images/android-30/google_apis_playstore/x86
      owner: wouter
      group: wouter
      mode: '0755'
      remote_src: yes

  - name: Creates directory Android/Sdk/build-tools/30.0.3
    file:
      path: /home/wouter/Android/Sdk/build-tools/30.0.3
      owner: wouter
      group: wouter
      mode: '0755'
      state: directory

  - name: Download build-tools/30.0.3
    ansible.builtin.unarchive:
      src: https://dl.google.com/android/repository/build-tools_r30.0.3-linux.zip
      dest: /home/wouter/Android/Sdk/build-tools/30.0.3
      owner: wouter
      group: wouter
      mode: '0755'
      remote_src: yes

  - name: Cleanup build-tools/30.0.3
    shell: mv /home/wouter/Android/Sdk/build-tools/30.0.3/android-*/*  /home/wouter/Android/Sdk/build-tools/30.0.3/ && rm -rf /home/wouter/Android/Sdk/build-tools/30.0.3/android-*

  - name: Creates directory Android/Sdk/build-tools/31.0.0
    file:
      path: /home/wouter/Android/Sdk/build-tools/31.0.0
      owner: wouter
      group: wouter
      mode: '0755'
      state: directory

  - name: Download build-tools/31.0.0
    ansible.builtin.unarchive:
      src: https://dl.google.com/android/repository/build-tools_r31-linux.zip
      dest: /home/wouter/Android/Sdk/build-tools/31.0.0
      owner: wouter
      group: wouter
      mode: '0755'
      remote_src: yes

  - name: Cleanup build-tools/31.0.0
    shell: mv /home/wouter/Android/Sdk/build-tools/31.0.0/android-*/*  /home/wouter/Android/Sdk/build-tools/31.0.0/ && rm -rf /home/wouter/Android/Sdk/build-tools/31.0.0/android-*

  #- name: Clean build-tools/31.0.0
  #  shell: rm -rf "/home/wouter/Android/Sdk/build-tools/31.0.0/android-12"

# https://docs.nativescript.org/environment-setup.html#linux-android
#  - name: download nodejs 16
#    become_user: wouter
#    shell: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

#  - name: install nodejs packages
#    become: yes
#    package:
#      name:
#        - nodejs

#  - name: install android sdk
#    package:
#      name:
#        - android-sdk
#        
#  - name: Download platform-tools-latest
#    get_url:
#      url: https://dl.google.com/android/repository/platform-tools-latest-linux.zip
#      dest: /tmp/platform-tools-latest-linux.zip

